[metric_fields.counter]
type = "struct"
optional = true
description = """\
A single value that can _only_ be incremented or reset, it cannot be decremented.\
"""

[metric_fields.counter.fields.name]
type = "string"
examples = ["login.count"]
optional = false
description = """\
The metric name.\
"""

[metric_fields.counter.fields.kind]
type = "string"
enum = ["absolute", "incremental"]
optional = false
description = """\
A metric could represent an already aggregated absolute value, or a relative (AKA delta) changes which occured between flush periods.\
"""

[metric_fields.counter.fields.tags]
type = "map"
examples = [{host = "my.host.com"}]
optional = false
description = """\
The metric tags.\
"""

[metric_fields.counter.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
Time metric was created/ingested.\
"""

[metric_fields.counter.fields.value]
type = "map"
examples = [{type = "counter", value = 10.2}]
optional = false
description = """\
Counter value.\
"""

[metric_fields.distribution]
type = "struct"
optional = true
description = """\
Also called a "timer". A `distribution` represents the frequency distribution of a \
value. This is commonly used for timings, helping to understand quantiles, max, \
min, and other aggregations.\
"""

[metric_fields.distribution.fields.name]
type = "string"
examples = ["duration_ms"]
optional = false
description = """\
The metric name.\
"""

[metric_fields.distribution.fields.kind]
type = "string"
enum = ["absolute", "incremental"]
optional = false
description = """\
A metric could represent an already aggregated absolute value, or a relative (AKA delta) changes which occured between flush periods.\
"""

[metric_fields.distribution.fields.tags]
type = "map"
examples = [{host = "my.host.com"}]
optional = false
description = """\
The metric tags.\
"""

[metric_fields.distribution.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
Time metric was created/ingested.\
"""

[metric_fields.distribution.fields.value]
type = "map"
examples = [{type = "distribution", values = [2.6], sample_rates = [1]}]
optional = false
description = """\
Distribution value.\
"""

[metric_fields.gauge]
type = "struct"
optional = true
description = """\
A gauge represents a point-in-time value that can increase and decrease. \
Gauges should be used to track fluctuations in values, like current memory or CPU usage.\
"""

[metric_fields.gauge.fields.name]
type = "string"
examples = ["memory_rss"]
optional = false
description = """\
The metric name.\
"""

[metric_fields.gauge.fields.kind]
type = "string"
enum = ["absolute", "incremental"]
optional = false
description = """\
A metric could represent an already aggregated absolute value, or a relative (AKA delta) changes which occured between flush periods.\
"""

[metric_fields.gauge.fields.tags]
type = "map"
examples = [{host = "my.host.com"}]
optional = false
description = """\
The metric tags.\
"""

[metric_fields.gauge.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
Time metric was created/ingested.\
"""

[metric_fields.gauge.fields.value]
type = "map"
examples = [{type = "gauge", value = 554222.0}]
optional = false
description = """\
Gauge value.\
"""

[metric_fields.set]
type = "struct"
optional = true
description = """\
A set represents a count of unique values, AKA the cardinality.\
"""

[metric_fields.set.fields.name]
type = "string"
examples = ["unique_users"]
optional = false
description = """\
The metric name.\
"""

[metric_fields.set.fields.kind]
type = "string"
enum = ["absolute", "incremental"]
optional = false
description = """\
A metric could represent an already aggregated absolute value, or a relative (AKA delta) changes which occured between flush periods.\
"""

[metric_fields.set.fields.tags]
type = "map"
examples = [{host = "my.host.com"}]
optional = false
description = """\
The metric tags.\
"""

[metric_fields.set.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
Time metric was created/ingested.\
"""

[metric_fields.set.fields.value]
type = "map"
examples = [{type = "set", values = ["127.0.0.1"]}]
optional = false
description = """\
Set value.\
"""
